### ISSUE TITLE
Uncaught Error: Failed opening required '/var/www/html/env-production/dictionaries/languages.php'

### ISSUE THREAD

**Issue by nandlalyadav57** [vbkunin/itop-docker#40]
With image: supervisions/itop:latest I am getting below error:

Did we forget to include that file /var/www/html/env-production/dictionaries/languages.php?

What should I do?

```
`Warning: require_once(/var/www/html/env-production/dictionaries/languages.php): Failed to open stream: No such file or directory in /var/www/html/core/metamodel.class.php on line 6401

Fatal error: Uncaught Error: Failed opening required '/var/www/html/env-production/dictionaries/languages.php' (include_path='/var/www/html/lib/pear/archive_tar:/var/www/html/lib/pear/console_getopt:/var/www/html/lib/pear/pear-core-minimal/src:/var/www/html/lib/pear/pear_exception:.:/usr/local/lib/php') in /var/www/html/core/metamodel.class.php:6401 Stack trace: #0 /var/www/html/core/metamodel.class.php(6313): MetaModel::LoadConfig() #1 /var/www/html/application/startup.inc.php(102): MetaModel::Startup() #2 /var/www/html/pages/UI.php(303): require_once('/var/www/html/a...') #3 {main} Next Error: Undefined constant "Combodo\iTop\Core\EventListener\EVENT_DOWNLOAD_DOCUMENT" in /var/www/html/sources/Core/EventListener/AttributeBlobEventListener.php:37 Stack trace: #0 /var/www/html/sources/Service/Events/EventService.php(48): Combodo\iTop\Core\EventListener\AttributeBlobEventListener->RegisterEventsAndListeners() #1 /var/www/html/core/metamodel.class.php(6331): Combodo\iTop\Service\Events\EventService::InitService() #2 /var/www/html/application/startup.inc.php(102): MetaModel::Startup() #3 /var/www/html/pages/UI.php(303): require_once('/var/www/html/a...') #4 {main} thrown in /var/www/html/sources/Core/EventListener/AttributeBlobEventListener.php on line 37
iTop: An error occurred, check server error log for more information.`
```

![image](https://github.com/vbkunin/itop-docker/assets/33649510/de9b911f-8148-46d8-9306-cc4dabf54a0e)

**Comment by vbkunin** [comment]
The supervisions/itop image is not mine.
