### ISSUE TITLE
Uncaught Error: Failed opening required '/var/www/html/env-production/dictionaries/languages.php'

### ISSUE THREAD

**Issue by dkurzelewski** [vbkunin/itop-docker#45]
Hello

I've got error in your docker image:

```
[Thu Oct 17 03:54:34.814709 2024] [php:warn] [pid 124] [client 172.18.0.6:34958] PHP Warning:  require_once(/var/www/html/env-production/dictionaries/languages.php): Failed to open stream: No such file or directory in /var/www/html/core/metamodel.class.php on line 6473, referer: http://10.6.0.16:81/
[Thu Oct 17 03:54:34.957345 2024] [php:error] [pid 124] [client 172.18.0.6:34958] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/env-production/dictionaries/languages.php' (include_path='/var/www/html/lib/pear/archive_tar:/var/www/html/lib/pear/console_getopt:/var/www/html/lib/pear/pear-core-minimal/src:/var/www/html/lib/pear/pear_exception:.:/usr/share/php') in /var/www/html/core/metamodel.class.php:6473\nStack trace:\n#0 /var/www/html/core/metamodel.class.php(6383): MetaModel::LoadConfig()\n#1 /var/www/html/application/startup.inc.php(103): MetaModel::Startup()\n#2 /var/www/html/pages/UI.php(308): require_once('...')\n#3 {main}\n\nNext Error: Undefined constant "Combodo\\iTop\\Core\\EventListener\\EVENT_DOWNLOAD_DOCUMENT" in /var/www/html/sources/Core/EventListener/AttributeBlobEventListener.php:37\nStack trace:\n#0 /var/www/html/sources/Service/Events/EventService.php(51): Combodo\\iTop\\Core\\EventListener\\AttributeBlobEventListener->RegisterEventsAndListeners()\n#1 /var/www/html/core/metamodel.class.php(6401): Combodo\\iTop\\Service\\Events\\EventService::InitService()\n#2 /var/www/html/application/startup.inc.php(103): MetaModel::Startup()\n#3 /var/www/html/pages/UI.php(308): require_once('...')\n#4 {main}\n  thrown in /var/www/html/sources/Core/EventListener/AttributeBlobEventListener.php on line 37
```

My docker-compose.yaml file content:

```
services:
  itop:
    image: vbkunin/itop
    container_name: itop
    restart: unless-stopped
    volumes:
      - './volumes/db:/var/lib/mysql'
      - './volumes/extensions:/var/www/html/extensions'
      - './volumes/config:/var/www/html/conf'
    networks:
      - npm-backend

networks:
  npm-backend:
    external: true
```

File that is in /var/www/html

```
docker exec -it itop bash
root@32ec5eaa0da6:/var/www/html# ls -al
total 1312
drwxr-xr-x  1 www-data www-data    4096 Sep 18 07:18 .
drwxr-xr-x  1 root     root        4096 Sep 29 12:09 ..
dr-xr-xr-x  3 www-data www-data    4096 Sep 18 07:18 addons
dr-xr-xr-x  4 www-data www-data    4096 Sep 18 07:18 application
-r--r--r--  1 www-data www-data     936 Sep 12 22:07 app.php
-r--r--r--  1 www-data www-data    1306 Sep 12 22:07 approot.inc.php
-r--r--r--  1 www-data www-data    3346 Sep 12 22:07 bootstrap.inc.php
drwxr-xr-x  3 www-data www-data    4096 Sep 18 10:58 conf
dr-xr-xr-x  3 www-data www-data    4096 Sep 18 07:18 core
dr-xr-xr-x  8 www-data www-data    4096 Sep 18 07:18 css
drwxr-xr-x  1 www-data www-data    4096 Oct 17 03:54 data
dr-xr-xr-x  3 www-data www-data    4096 Sep 18 07:18 datamodels
dr-xr-xr-x  4 www-data www-data    4096 Sep 18 07:18 dictionaries
drwxr-xr-x  2 root     root        4096 Sep 18 10:54 extensions
dr-xr-xr-x  9 www-data www-data    4096 Sep 18 07:18 images
-r--r--r--  1 www-data www-data    1345 Sep 12 22:06 index.php
dr-xr-xr-x 15 www-data www-data    4096 Sep 18 07:18 js
dr-xr-xr-x 23 www-data www-data    4096 Sep 18 07:18 lib
drwxr-xr-x  1 www-data www-data    4096 Oct 17 03:54 log
-r--r--r--  1 www-data www-data 1215216 Sep 13 10:44 manifest.xml
dr-xr-xr-x 34 www-data www-data    4096 Sep 18 07:18 node_modules
dr-xr-xr-x  2 www-data www-data    4096 Sep 18 07:18 pages
dr-xr-xr-x  2 www-data www-data    4096 Sep 18 07:18 portal
dr-xr-xr-x  3 www-data www-data    4096 Sep 18 07:18 resources
dr-xr-xr-x  7 www-data www-data    4096 Sep 18 07:18 setup
dr-xr-xr-x 10 www-data www-data    4096 Sep 18 07:18 sources
dr-xr-xr-x  2 www-data www-data    4096 Sep 18 07:18 synchro
dr-xr-xr-x  6 www-data www-data    4096 Sep 18 07:18 templates
-r--r--r--  1 www-data www-data     615 Mar  6  2023 web.config
dr-xr-xr-x  2 www-data www-data    4096 Sep 18 07:18 webservices
```

Docker image details:

```
docker images | grep itop
vbkunin/itop                                      latest              9391897b3edb   2 weeks ago    665MB

docker image inspect 9391897b3edb
[
    {
        "Id": "sha256:9391897b3edbfe6fba82e3d6200e3cd27ce32e0a46e7b7421dcbf212f3e0b969",
        "RepoTags": [
            "vbkunin/itop:latest"
        ],
        "RepoDigests": [
            "vbkunin/itop@sha256:bf3746c9b12ea4439394088ad57de8d6b2d9b271a10ea2220f1ede07d59fe93a"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2024-09-29T12:11:23.244196597Z",
        "DockerVersion": "",
        "Author": "",
        "Config": {
            "Hostname": "",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3306/tcp": {},
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "DEBIAN_FRONTEND=teletype",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8"
            ],
            "Cmd": [
                "/sbin/my_init"
            ],
            "Healthcheck": {
                "Test": [
                    "CMD-SHELL",
                    "curl -f http://localhost/ || exit 1"
                ],
                "Interval": 300000000000,
                "Timeout": 3000000000
            },
            "ArgsEscaped": true,
            "Image": "",
            "Volumes": {
                "/var/lib/mysql": {}
            },
            "WorkingDir": "/var/www/html",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "title": "Docker image with Combodo iTop",
                "url": "https://github.com/vbkunin/itop-docker",
                "version": "1.1.0"
            }
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 665339552,
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/d0fcf6524b86b286d4ebfa29516ab307f6cc626cb69498223cb0dfc92d4263a8/diff:/var/lib/docker/overlay2/4a02fcd8a3adbebb9b453829e8af63e2a1938ada8fc3ed8bac7246010bfa4f5e/diff:/var/lib/docker/overlay2/0c4c7c2beede04dcd012e4399ace01ff1802fd89e64ba202c01b30ead5430c54/diff:/var/lib/docker/overlay2/1af970e1a81a8705e3bab2a26a8e3adab29f2fd90a2d0273cbfe510f5aa98e5e/diff:/var/lib/docker/overlay2/8aa7ae3f21abfffa46f056b8aa7c9965d200744b64522d44e4d2a504a20ec0c5/diff:/var/lib/docker/overlay2/94b5e16e39acb38f022d4416a2eaa2a05eec5d774a606c83473f56ae9b12c76c/diff:/var/lib/docker/overlay2/c28dd80a43371fe6f119b1a83680bff6a1a550950063b15825b91e04020027bc/diff:/var/lib/docker/overlay2/4267bf23a2cf97d017683478fa74eb5afeb8eab509a6bbbf8c82b915e513bd51/diff:/var/lib/docker/overlay2/32477c180211d4b272e159d059d7bc8ac991c9fc24cca72d2a492355a53cb7eb/diff:/var/lib/docker/overlay2/acb6672c4cfa69434948a6ddbaec2ed6d09be1df0adc16cbca387e9ae996001c/diff:/var/lib/docker/overlay2/40fbed677b89c638dd160be97d2ebe0333d687629eafb9f08b4aafb7bf31356f/diff:/var/lib/docker/overlay2/59a49c7bdd6bc8b5880e12ee90297068f344219b29d67dc412c53841af036c64/diff:/var/lib/docker/overlay2/4b4eda7e18ff01b291047445e6fc41ac7af38563bea31fb6e32f93c0a276e2f0/diff:/var/lib/docker/overlay2/783c9a25da296eff828fd8b08eb920a7abc39694d4e26e3c6f884651f9236525/diff:/var/lib/docker/overlay2/2696ad1f3a1c6def6ced7d1cc3de6b3ade15dabac11fbcbd12975c81243aae85/diff:/var/lib/docker/overlay2/361fba295e0f628b4c0b43378028ea7284de4df0420d238f078fb4219e786e73/diff",
                "MergedDir": "/var/lib/docker/overlay2/66d1ecf012dda3b7d2290b4a7a2aa2d0afc603f84740fe2fd20f2d6fbaa67163/merged",
                "UpperDir": "/var/lib/docker/overlay2/66d1ecf012dda3b7d2290b4a7a2aa2d0afc603f84740fe2fd20f2d6fbaa67163/diff",
                "WorkDir": "/var/lib/docker/overlay2/66d1ecf012dda3b7d2290b4a7a2aa2d0afc603f84740fe2fd20f2d6fbaa67163/work"
            },
            "Name": "overlay2"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:7f5cbd8cc787c8d628630756bcc7240e6c96b876c2882e6fc980a8b60cdfa274",
                "sha256:31ee2011b35056e3f2d13588f0339c10cc52aa3aa012115a898f3c0f2f2cea12",
                "sha256:bcb7e1bba665108211179067843fd5669a615985876d714fe6b514623f0646f3",
                "sha256:40bf55788c5131a3092f90abbcd471a453ea8cb9876478ec94be17bca0d6c9a0",
                "sha256:9af9a5930a16743ec3085155dc0c949fa0fcee6771b1af2a26f17a96494b51de",
                "sha256:118792c2a38945ce760770375b62340306a3c1aeb1194826516c547885a6b749",
                "sha256:539b802890c8692552e1da69b5445eb03bb0cec54b4bc39a430f112bf6833d70",
                "sha256:5095a6f1aae184bf70ef697712648e930cfaa2fd801bbcf9655df0111e505175",
                "sha256:dbf97e4e7f62dc7369d6c18224a83a864eb49fae620a29bcabcae06ede1f6c7d",
                "sha256:3ebb45015f992d4a7e5e964690eca24a8fb0df7746f7083c12c0d5cf80aa8c54",
                "sha256:fe279c65cf3de9f8f35f802942de83efede8aea3a5bb947681e68318636602fd",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:39f801331bacefaa7faa7a37f9087793b1e297331351dcb2542fe95bfc42229b",
                "sha256:b158126fd3eb4e9eaebc93901d109f5f1168bcd373eb8944cdd3b5f546dca420",
                "sha256:5e6d0440c5f7d8007910ba9b73e78c38a019e558da424b1053cc849e1d0c210c",
                "sha256:4118c962db5a3a43f1c2302d5ff3398216c210b0e784ce8abf95f863e465b605",
                "sha256:a352baba168251ddc48a1ae32089171d957052ecc46330412404ed1f15050b60"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

```

**Comment by vbkunin** [comment]
Hi! The problem is not with the image but with your config. Where is the env-production folder? Have you done the installation? Why you're trying to connect on 81 port? By default the image expose 80 port and apache is listening on it.
